version: "3.9"
services:
    postgres:
        image: postgres:15
        restart: always
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${PG_Username}
            - POSTGRES_PASSWORD=${PG_Password}
            - POSTGRES_DB=${MAKI_dbName}
    
    postgres_backup:
        image: eeshugerman/postgres-backup-s3:15
        restart: always
        environment:
            - SCHEDULE=@daily
            - S3_ENDPOINT=${S3_endpoint}
            - S3_ACCESS_KEY_ID=${S3_KeyId}
            - S3_SECRET_ACCESS_KEY=${S3_AccessKey}
            - S3_BUCKET=${S3_Bucket}
            - S3_PREFIX=backup
            - POSTGRES_HOST=postgres
            - POSTGRES_DATABASE=${PG_dbName}
            - POSTGRES_USER=${PG_Username}
            - POSTGRES_PASSWORD=${PG_Password}
        depends_on: 
            - postgres

    redis:
        image: redis:7-alpine
        restart: always
        volumes: 
            - ./data/redis:/data

    maki-model:
        image: rickycorte/maki-model:release
        restart: always
        volumes: 
            - ./data:/data
        environment:
            - MAKI_PersistentPath=/data
            - MAKI_ModelHost=[::]:50051"
            - MAKI_ModelWorkers=10
    
    maki-model-retrainer:
        image: rickycorte/maki-model:release
        restart: always
        volumes: 
            - ./data:/data
        environment:
            - MAKI_IsRetrainer=true
            - MAKI_PersistentPath=/data
            - MAKI_PostgresUrl=host=postgres user=${PG_Username} password=${PG_Password} dbname=${PG_dbName}
            - MAKI_RetrainEverySeconds=604800
        depends_on: 
            - postgres

    maki-anime-updater:
        image: rickycorte/maki-data-updater:release
        restart: always
        environment:
            - MAKI_UpdaterDatabaseConnection=postgres user=${PG_Username} password=${PG_Password} dbname=${PG_dbName}
            - MAKI_UpdaterRunEverySeconds=900
        depends_on:
            - maki

    maki:
        image: rickycorte/maki-api:release
        restart: always
        environment:
            - MAKI_SqlDBConnection=postgres user=${PG_Username} password=${PG_Password} dbname=${PG_dbName}
            - MAKI_RedisDBConnection=redis://redis
            - MAKI_ServerAddress=:5000
            - MAKI_RecommendationServiceAddress=maki-model:50051
            - MAKI_MaxRecommendations=100
            - MAKI_DefaultRecommendations=12
            - MAKI_ListIsOldAfterSeconds=600
            - MAKI_RecommendationCacheExpireSeconds=86400
            - MAKI_CacheClearAfterSeconds=604800
        depends_on: 
            - postgres
            - redis
            - maki-model
    nginx:
        image: nginx
        restart: always
        ports: 
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./cert:/etc/ssl
        depends_on: 
            - maki
